%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: F:\github\wearable-jacket\matlab\IEEE_sensors\data_matched\LA,LF,RA,RF\Y\60_WISE+turntable_11-22-2019 20-58.txt
%
% Auto-generated by MATLAB on 23-Nov-2019 05:37:17

%% Setup the Import Options
clc;clear all;close all
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("F:\github\wearable-jacket\matlab\IEEE_sensors\data_matched\LA,LF,RA,RF\Y\LF_good.txt", opts);

%% Convert to output type
Time = tbl.VarName1;
VarName2 = tbl.VarName2;
VarName3 = tbl.VarName3;
VarName4 = tbl.VarName4;
VarName5 = tbl.VarName5;
VarName6 = tbl.VarName6;
VarName7 = tbl.VarName7;
VarName8 = tbl.VarName8;
VarName9 = tbl.VarName9;
VarName10 = tbl.VarName10;
VarName11 = tbl.VarName11;
VarName12 = tbl.VarName12;
VarName13 = tbl.VarName13;
VarName14 = tbl.VarName14;
VarName15 = tbl.VarName15;
VarName16 = tbl.VarName16;
VarName17 = tbl.VarName17;
VarName18 = tbl.VarName18;
VarName19 = tbl.VarName19;
VarName20 = tbl.VarName20;
VarName21 = tbl.VarName21;
LF = tbl.VarName22;
RF = tbl.VarName23;
LA = tbl.VarName24;
RA = tbl.VarName25;


LF = LF-min(LF);
% LF = LF-2.5;
% for i=1:length(LF) %for 60_WISE+turntable_11-22-2019 21-21
% if LF(i)~=0
%     LF(i) = LF(i)-[3.40729200000000];
% end
% end
RF = RF-min(RF);
% RF = RF-2.5;
LA = LA-min(LA);
% LA = LA-2.5;
% for i=1:length(LA) %for 60_WISE+turntable_11-22-2019 21-21
% if LA(i)~=0
%     LA(i) = LA(i)-[3.82183400000000];
% end
% end
RA = RA-min(RA);
% RA = RA-2.5;

%% Clear temporary variables
clear opts tbl


LW = 2;
figure(1)
subplot(4,1,1)
lf = plot(Time,LF,'Color','r','LineWidth',LW,'DisplayName','LF')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
axis([0 300 -1 1])
subplot(4,1,2)
rf = plot(Time,RF,'Color','g','LineWidth',LW,'DisplayName','RF')
hold on
axis([0 300 -1 1])
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
subplot(4,1,3)
la = plot(Time,LA,'Color','b','LineWidth',LW,'DisplayName','LA')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
axis([0 300 -1 1])
subplot(4,1,4)
ra = plot(Time,RA,'Color','k','LineWidth',LW,'DisplayName','RA')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
axis([0 300 -1 1])
lgd = legend([lf,rf,la,ra],'FontSize',15)
lgd.Orientation = 'horizontal'