function [Timestamp, Kinect_LeftShoulder_ExtFlex, IMU_LeftShoulder_ExtFlex, Kinect_LeftShoulder_AbdAdd, IMU_LeftShoulder_AbdAdd, Kinect_LeftShoulder_IntExt, IMU_LeftShoulder_IntExt, Kinect_LeftElbow_ExtFlex, IMU_LeftElbow_ExtFlex, IMU_LeftElbow_ProSup, Kinect_RightShoulder_ExtFlex, IMU_RightShoulder_ExtFlex, Kinect_RightShoulder_AbdAdd, IMU_RightShoulder_AbdAdd, Kinect_RightShoulder_IntExt, IMU_RightShoulder_IntExt, Kinect_RightElbow_ExtFlex, IMU_RightElbow_ExtFlex, IMU_RightElbow_ProSup] = importtextkinimu(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [TIMESTAMP, KINECT_LEFTSHOULDER_EXTFLEX, IMU_LEFTSHOULDER_EXTFLEX,
%  KINECT_LEFTSHOULDER_ABDADD, IMU_LEFTSHOULDER_ABDADD,
%  KINECT_LEFTSHOULDER_INTEXT, IMU_LEFTSHOULDER_INTEXT,
%  KINECT_LEFTELBOW_EXTFLEX, IMU_LEFTELBOW_EXTFLEX,
%  IMU_LEFTELBOW_PROSUP, KINECT_RIGHTSHOULDER_EXTFLEX,
%  IMU_RIGHTSHOULDER_EXTFLEX, KINECT_RIGHTSHOULDER_ABDADD,
%  IMU_RIGHTSHOULDER_ABDADD, KINECT_RIGHTSHOULDER_INTEXT,
%  IMU_RIGHTSHOULDER_INTEXT, KINECT_RIGHTELBOW_EXTFLEX,
%  IMU_RIGHTELBOW_EXTFLEX, IMU_RIGHTELBOW_PROSUP] =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [TIMESTAMP, KINECT_LEFTSHOULDER_EXTFLEX, IMU_LEFTSHOULDER_EXTFLEX,
%  KINECT_LEFTSHOULDER_ABDADD, IMU_LEFTSHOULDER_ABDADD,
%  KINECT_LEFTSHOULDER_INTEXT, IMU_LEFTSHOULDER_INTEXT,
%  KINECT_LEFTELBOW_EXTFLEX, IMU_LEFTELBOW_EXTFLEX,
%  IMU_LEFTELBOW_PROSUP, KINECT_RIGHTSHOULDER_EXTFLEX,
%  IMU_RIGHTSHOULDER_EXTFLEX, KINECT_RIGHTSHOULDER_ABDADD,
%  IMU_RIGHTSHOULDER_ABDADD, KINECT_RIGHTSHOULDER_INTEXT,
%  IMU_RIGHTSHOULDER_INTEXT, KINECT_RIGHTELBOW_EXTFLEX,
%  IMU_RIGHTELBOW_EXTFLEX, IMU_RIGHTELBOW_PROSUP] = IMPORTFILE1(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Timestamp, Kinect_LeftShoulder_ExtFlex, IMU_LeftShoulder_ExtFlex, Kinect_LeftShoulder_AbdAdd, IMU_LeftShoulder_AbdAdd, Kinect_LeftShoulder_IntExt, IMU_LeftShoulder_IntExt, Kinect_LeftElbow_ExtFlex, IMU_LeftElbow_ExtFlex, IMU_LeftElbow_ProSup, Kinect_RightShoulder_ExtFlex, IMU_RightShoulder_ExtFlex, Kinect_RightShoulder_AbdAdd, IMU_RightShoulder_AbdAdd, Kinect_RightShoulder_IntExt, IMU_RightShoulder_IntExt, Kinect_RightElbow_ExtFlex, IMU_RightElbow_ExtFlex, IMU_RightElbow_ProSup] = importfile1("F:\github\wearable-jacket\matlab\kinect+imudata\wearable+kinecttesting_05-30-2019 00-18.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-May-2019 05:16:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "Kinect_LeftShoulder_ExtFlex", "IMU_LeftShoulder_ExtFlex", "Kinect_LeftShoulder_AbdAdd", "IMU_LeftShoulder_AbdAdd", "Kinect_LeftShoulder_IntExt", "IMU_LeftShoulder_IntExt", "Kinect_LeftElbow_ExtFlex", "IMU_LeftElbow_ExtFlex", "IMU_LeftElbow_ProSup", "Kinect_RightShoulder_ExtFlex", "IMU_RightShoulder_ExtFlex", "Kinect_RightShoulder_AbdAdd", "IMU_RightShoulder_AbdAdd", "Kinect_RightShoulder_IntExt", "IMU_RightShoulder_IntExt", "Kinect_RightElbow_ExtFlex", "IMU_RightElbow_ExtFlex", "IMU_RightElbow_ProSup"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Timestamp = tbl.Timestamp;
Kinect_LeftShoulder_ExtFlex = tbl.Kinect_LeftShoulder_ExtFlex;
IMU_LeftShoulder_ExtFlex = tbl.IMU_LeftShoulder_ExtFlex;
Kinect_LeftShoulder_AbdAdd = tbl.Kinect_LeftShoulder_AbdAdd;
IMU_LeftShoulder_AbdAdd = tbl.IMU_LeftShoulder_AbdAdd;
Kinect_LeftShoulder_IntExt = tbl.Kinect_LeftShoulder_IntExt;
IMU_LeftShoulder_IntExt = tbl.IMU_LeftShoulder_IntExt;
Kinect_LeftElbow_ExtFlex = tbl.Kinect_LeftElbow_ExtFlex;
IMU_LeftElbow_ExtFlex = tbl.IMU_LeftElbow_ExtFlex;
IMU_LeftElbow_ProSup = tbl.IMU_LeftElbow_ProSup;
Kinect_RightShoulder_ExtFlex = tbl.Kinect_RightShoulder_ExtFlex;
IMU_RightShoulder_ExtFlex = tbl.IMU_RightShoulder_ExtFlex;
Kinect_RightShoulder_AbdAdd = tbl.Kinect_RightShoulder_AbdAdd;
IMU_RightShoulder_AbdAdd = tbl.IMU_RightShoulder_AbdAdd;
Kinect_RightShoulder_IntExt = tbl.Kinect_RightShoulder_IntExt;
IMU_RightShoulder_IntExt = tbl.IMU_RightShoulder_IntExt;
Kinect_RightElbow_ExtFlex = tbl.Kinect_RightElbow_ExtFlex;
IMU_RightElbow_ExtFlex = tbl.IMU_RightElbow_ExtFlex;
IMU_RightElbow_ProSup = tbl.IMU_RightElbow_ProSup;
end