function time = importtime(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  VARNAME1 = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as column vectors.
%
%  VARNAME1 = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  VarName1 = importfile1("F:\github\wearable-jacket\matlab\IEEE_sensors\data_matched\LA,RA\Y\20_WISE+turntable_08-09-2019 17-24.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Aug-2019 18:51:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15"];
opts.SelectedVariableNames = "VarName1";
opts.VariableTypes = ["double", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];
opts = setvaropts(opts, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
time = tbl.VarName1;
end