%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: F:\github\wearable-jacket\matlab\IEEE_sensors\data_matched\LF,RF\Y\80_WISE+turntable_08-09-2019 17-41.txt
%
% Auto-generated by MATLAB on 22-Nov-2019 18:56:25

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = [1, 171];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("F:\github\wearable-jacket\matlab\IEEE_sensors\data_matched\LF,RF\Z\80_WISE+turntable_08-09-2019 18-17.txt", opts);

%% Convert to output type
Time = tbl.VarName1;
VarName18 = tbl.VarName18;
VarName19 = tbl.VarName19;
VarName20 = tbl.VarName20;
VarName21 = tbl.VarName21;
VarName22 = tbl.VarName22;
VarName23 = tbl.VarName23;
VarName24 = tbl.VarName24;
VarName25 = tbl.VarName25;
VarName26 = tbl.VarName26;
VarName27 = tbl.VarName27;
VarName28 = tbl.VarName28;
VarName29 = tbl.VarName29;
LF = tbl.VarName30;
RF = tbl.VarName31;
LF = LF-min(LF);
RF = RF-min(RF);

%% Clear temporary variables
clear opts tbl

LW = 2;
figure(1)
subplot(2,1,1)
lf = plot(Time,LF,'Color','r','LineWidth',LW,'DisplayName','LF')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
subplot(2,1,2)
rf = plot(Time,RF,'Color','g','LineWidth',LW,'DisplayName','RF')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)

lgd = legend([lf,rf],'FontSize',15)
lgd.Orientation = 'horizontal'
