%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: F:\github\wearable-jacket\matlab\IEEE_spmb\data_matched\A,B,C,D\Z\80_WISE+turntable_08-09-2019 16-09.txt
%
% Auto-generated by MATLAB on 22-Nov-2019 18:26:15

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("F:\github\wearable-jacket\matlab\IEEE_spmb\data_matched\A,B,C,D\Y\40_WISE+turntable_07-10-2019 16-38.txt", opts);

%% Convert to output type
Time = tbl.VarName1;
VarName2 = tbl.VarName2;
VarName3 = tbl.VarName3;
VarName4 = tbl.VarName4;
VarName5 = tbl.VarName5;
VarName6 = tbl.VarName6;
VarName7 = tbl.VarName7;
VarName8 = tbl.VarName8;
VarName9 = tbl.VarName9;
VarName10 = tbl.VarName10;
VarName11 = tbl.VarName11;
VarName12 = tbl.VarName12;
VarName13 = tbl.VarName13;
VarName14 = tbl.VarName14;
VarName15 = tbl.VarName15;
VarName16 = tbl.VarName16;
VarName17 = tbl.VarName17;
LF = tbl.VarName18*180/pi;
RF = tbl.VarName19*180/pi;
LA = tbl.VarName20*180/pi;
RA = tbl.VarName21*180/pi;
LF = LF-min(LF);
RF = RF-min(RF);
LA = LA-min(LA);
RA = RA-min(RA);


%% Clear temporary variables
clear opts tbl
LW = 2;
figure(1)
subplot(2,2,1)
lf = plot(Time,LF,'Color','r','LineWidth',LW,'DisplayName','LF')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
subplot(2,2,2)
rf = plot(Time,RF,'Color','g','LineWidth',LW,'DisplayName','RF')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
subplot(2,2,3)
la = plot(Time,LA,'Color','b','LineWidth',LW,'DisplayName','LA')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
subplot(2,2,4)
ra = plot(Time,RA,'Color','k','LineWidth',LW,'DisplayName','RA')
hold on
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)

lgd = legend([lf,rf,la,ra],'FontSize',15)
lgd.Orientation = 'horizontal'
