%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: F:\github\wearable-jacket\matlab\IEEE_sensors\JCS_data\instrreset\instrreset_WISE+JCS_02-04-2020 21-31.txt
%
% Auto-generated by MATLAB on 05-Feb-2020 07:22:37

clc
clear all
close all
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("F:\github\wearable-jacket\matlab\IEEE_sensors\JCS_data\instrreset\instrreset_WISE+JCS_02-04-2020 21-25.txt", opts);


T = tbl.VarName1;
Lsp = tbl.VarName2;
Lse = tbl.VarName3;
Lie = tbl.VarName4;
Lca = tbl.VarName5;
Lelbfe = tbl.VarName6;
Lps = tbl.VarName7;
Rsp = tbl.VarName8;
Rse = tbl.VarName9;
Rie = tbl.VarName10;
Rca = tbl.VarName11;
Relbfe = tbl.VarName12;
Rps = tbl.VarName13;

clear opts tbl

%%

loc = find(round(T)==15);
T(1:loc)=[];
Lie(1:loc)=[];
Lse(1:loc)=[];
Lsp(1:loc)=[];
Lca(1:loc)=[];
Lelbfe(1:loc)=[];
Lps(1:loc)=[];
loc2 = find(round(Lse)<=10);
T(loc2)=[];
Lie(loc2)=[];
Lse(loc2)=[];
Lsp(loc2)=[];
Lca(loc2)=[];
Lelbfe(loc2)=[];
Lps(loc2)=[];
line = -180:1:180;
t = ones(size(line));
figure(1)
subplot(2,1,1)
axis([0 120 -120 180])
hold on
LSE = plot(T,Lse,'-r','LineWidth',2,'DisplayName','Shoulder Elevation');
LSP = plot(T,Lsp,'-g','LineWidth',2,'DisplayName','Shoulder Plane');
LIE = plot(T,Lie,'-b','LineWidth',2,'DisplayName','Shoulder Int.-Ext. Rotation');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)

subplot(2,1,2)
axis([0 120 -90 90])
hold on
LCA  = plot(T,Lca,'-c','LineWidth',2,'DisplayName','Carry angle');
LELBFE  = plot(T,Lelbfe,'-m','LineWidth',2,'DisplayName','Forearm Flex.-Ext.');
LPS = plot(T,Lps,'-k','LineWidth',2,'DisplayName','Forearm Pro.-Sup.');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)

lgd = legend([LSE,LSP,LIE,LELBFE,LPS,LCA],'FontSize',15);
lgd.Orientation = 'horizontal';

[P_lsp]=polyfit(Lse,Lsp,1);
[P_lie]=polyfit(Lse,Lie,1);
[P_lps]=polyfit(Lse,Lps,1);
[P_lelbfe]=polyfit(Lse,Lelbfe,1);
%%

lse_new = -90:0.1:180;
lsp_new = zeros(size(lse_new));
lie_new = zeros(size(lse_new));
lps_new = zeros(size(lse_new));
lelbfe_new = zeros(size(lse_new));
lsp_new = P_lsp(1)*lse_new+P_lsp(2);
lie_new = P_lie(1)*lse_new+P_lie(2);
lps_new = P_lps(1)*lse_new+P_lps(2);
lelbfe_new = P_lelbfe(1)*lse_new+P_lelbfe(2);
Lefthand = zeros(length(Lse),5);
LBD = [lse_new;lsp_new;lie_new;lps_new;lelbfe_new];

for i=1:length(Lse)
    Lefthand(i,1) = lse_new(find(lse_new>=round(Lse(i),1),1));
    Lefthand(i,2) = lsp_new(find(lse_new>=round(Lse(i),1),1));
    Lefthand(i,3) = lie_new(find(lse_new>=round(Lse(i),1),1));
    Lefthand(i,4) = lps_new(find(lse_new>=round(Lse(i),1),1));
    Lefthand(i,5) = lelbfe_new(find(lse_new>=round(Lse(i),1),1));
end
figure(2)
subplot(2,1,1)
axis([0 120 -120 180])
hold on
LSE1 = plot(T,Lse,'-r','LineWidth',1,'DisplayName','Shoulder Elevation');
LSP1 = plot(T,Lsp,'-g','LineWidth',1,'DisplayName','Shoulder Plane');
LIE1 = plot(T,Lie,'-b','LineWidth',1,'DisplayName','Shoulder Int.-Ext. Rotation');
LSE2 = plot(T,Lefthand(:,1),'--r','LineWidth',1,'DisplayName','Shoulder Elevation');
LSP2 = plot(T,Lefthand(:,2),'--g','LineWidth',1,'DisplayName','Shoulder Plane');
LIE2 = plot(T,Lefthand(:,3),'--b','LineWidth',1,'DisplayName','Shoulder Int.-Ext. Rotation');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)

subplot(2,1,2)
axis([0 120 -90 90])
hold on
LCA1 = plot(T,Lca,'-c','LineWidth',1,'DisplayName','Carry angle');
LELBFE1  = plot(T,Lelbfe,'-m','LineWidth',1,'DisplayName','Forearm Flex.-Ext.');
LPS1 = plot(T,Lps,'-k','LineWidth',1,'DisplayName','Forearm Pro.-Sup.');
LCA2  = plot(T,Lca,'--c','LineWidth',1,'DisplayName','Carry angle');
LELBFE2  = plot(T,Lefthand(:,5),'--m','LineWidth',1,'DisplayName','Forearm Flex.-Ext.');
LPS2 = plot(T,Lefthand(:,4),'--k','LineWidth',1,'DisplayName','Forearm Pro.-Sup.');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)

Lsp_Kend = corr(Lsp,Lefthand(:,2))
Lie_Kend = corr(Lie,Lefthand(:,3))
Lelbfe_Kend = corr(Lelbfe,Lefthand(:,5))
Lps_Kend = corr(Lps,Lefthand(:,4))

Lsp_RMSE = signal_RMSE(Lsp,Lefthand(:,2))
Lie_RMSE = signal_RMSE(Lie,Lefthand(:,3))
Lelbfe_RMSE = signal_RMSE(Lelbfe,Lefthand(:,5))
Lps_RMSE = signal_RMSE(Lps,Lefthand(:,4))