clc
clear all
close all

% Script for importing data from the following text file:
%
%    filename: F:\github\wearable-jacket\matlab\IEEE_sensors\JCS_data\instrreset1\instrreset1_WISE+JCS_02-06-2020 22-24.txt
%
% Auto-generated by MATLAB on 07-Feb-2020 05:44:08

opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("F:\github\wearable-jacket\matlab\IEEE_sensors\JCS_data\instrreset1\instrreset1_WISE+JCS_02-06-2020 22-24.txt", opts);
T_1 = tbl.VarName1;
Lsp_1 = tbl.VarName2;
Lse_1 = tbl.VarName3;
Lie_1 = tbl.VarName4;
Lca_1 = tbl.VarName5;
Lelbfe_1 = tbl.VarName6;
Lps_1 = tbl.VarName7;
VarName8 = tbl.VarName8;
VarName9 = tbl.VarName9;
VarName10 = tbl.VarName10;
VarName11 = tbl.VarName11;
VarName12 = tbl.VarName12;
VarName13 = tbl.VarName13;
clear opts tbl VarName8 VarName9 VarName10 VarName11 VarName12 VarName13
opts = delimitedTextImportOptions("NumVariables", 13);
opts.DataLines = [1, Inf];
opts.Delimiter = ",";
% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
tbl = readtable("F:\github\wearable-jacket\matlab\IEEE_sensors\JCS_data\instrreset1\instrreset1_WISE+JCS_02-06-2020 22-26.txt", opts);
T_2 = tbl.VarName1;
Lsp_2 = tbl.VarName2;
Lse_2 = tbl.VarName3;
Lie_2 = tbl.VarName4;
Lca_2 = tbl.VarName5;
Lelbfe_2 = tbl.VarName6;
Lps_2 = tbl.VarName7;
VarName8 = tbl.VarName8;
VarName9 = tbl.VarName9;
VarName10 = tbl.VarName10;
VarName11 = tbl.VarName11;
VarName12 = tbl.VarName12;
VarName13 = tbl.VarName13;
clear opts tbl VarName8 VarName9 VarName10 VarName11 VarName12 VarName13
lfe_lookup = load('lfe_lookup.mat');
LH_lookup = lfe_lookup.LFE;
LH_t1 = [T_1';Lse_1';Lsp_1';Lie_1';Lps_1';Lelbfe_1'];
LH_t2 = [T_2';Lse_2';Lsp_2';Lie_2';Lps_2';Lelbfe_2'];
%%

loc1 = find(T_1>=9.5,1);
loc2 = find(T_1>=34.75,1);
LH_t1(:,loc2:end)=[];
LH_t1(:,1:loc1)=[];
T_1(loc2:end)=[];
T_1(1:loc1)=[];
Lse_1(loc2:end)=[];
Lse_1(1:loc1)=[];
Lsp_1(loc2:end)=[];
Lsp_1(1:loc1)=[];
Lie_1(loc2:end)=[];
Lie_1(1:loc1)=[];
Lca_1(loc2:end)=[];
Lca_1(1:loc1)=[];
Lelbfe_1(loc2:end)=[];
Lelbfe_1(1:loc1)=[];
Lps_1(loc2:end)=[];
Lps_1(1:loc1)=[];

cost=zeros(size(LH_t1));
costsum = zeros(1,length(cost));
for i=1:length(LH_t1)

cost(1,i) = LH_t1(1,i);
loc3 = find(LH_lookup(1,:)>=round(LH_t1(2,i)),1);
cost(2,i) = abs(LH_t1(2,i)-LH_lookup(1,loc3));
cost(3,i) = abs(LH_t1(3,i)-LH_lookup(2,loc3));
cost(4,i) = abs(LH_t1(4,i)-LH_lookup(3,loc3));
cost(5,i) = abs(LH_t1(5,i)-LH_lookup(4,loc3));
cost(6,i) = abs(LH_t1(6,i)-LH_lookup(5,loc3));
costsum(i) = cost(3,i)+cost(4,i)+cost(5,i)+cost(6,i);
cost(2:6,i) = cost(2:6,i)/costsum(i);
end

costindsum = zeros(4,2);
for j=1:4
   costindsum(j,1) = sum(cost(j+2,:)); 
end

figure(1)
subplot(3,1,1)
axis([9.5 34.55 -120 180])
hold on
LSE = plot(LH_t1(1,:),LH_t1(2,:),'-r','LineWidth',2,'DisplayName','Shoulder Elevation (SE)');
LSP = plot(LH_t1(1,:),LH_t1(3,:),'-g','LineWidth',2,'DisplayName','Shoulder Plane (SP)');
LIE = plot(LH_t1(1,:),LH_t1(4,:),'-b','LineWidth',2,'DisplayName','Shoulder Int.-Ext. Rotation (IE)');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
lgd1 = legend([LSE,LSP,LIE],'FontSize',15);
lgd1.Orientation = 'horizontal';
subplot(3,1,2)
axis([9.5 34.55 -90 90])
hold on
LCA  = plot(LH_t1(1,:),Lca_1,'-c','LineWidth',2,'DisplayName','Carry angle (CA)');
LELBFE  = plot(LH_t1(1,:),LH_t1(5,:),'-m','LineWidth',2,'DisplayName','Elbow Flex.-Ext. (FE)');
LPS = plot(LH_t1(1,:),LH_t1(6,:),'-k','LineWidth',2,'DisplayName','Forearm Pro.-Sup. (PS)');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
lgd2 = legend([LCA,LELBFE,LPS],'FontSize',15);
lgd2.Orientation = 'horizontal';
subplot(3,1,3)
axis([9.5 34.55 0 1])
hold on
% LSE_C = plot(cost(1,:),cost(2,:),'-r','LineWidth',2,'DisplayName','SE_{cost}');
LSP_C = plot(cost(1,:),cost(3,:),'-g','LineWidth',2,'DisplayName','SP_{cost}');
LIE_C = plot(cost(1,:),cost(4,:),'-b','LineWidth',2,'DisplayName','IE_{cost}');
LPS_C = plot(cost(1,:),cost(5,:),'-k','LineWidth',2,'DisplayName','PS_{cost}');
LELBFE_C = plot(cost(1,:),cost(6,:),'-m','LineWidth',2,'DisplayName','FE_{cost}');
% plot(cost(1,:),costsum,'-r','LineWidth',2,'DisplayName','fe_cost');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
lgd2 = legend([LSP_C,LIE_C,LPS_C,LELBFE_C],'FontSize',15);
lgd2.Orientation = 'horizontal';
% figure(2)
% bar([costindsum(1) costindsum(2) costindsum(3) costindsum(4)])
% hold on

%%

loc1 = find(T_2>=22,1);
loc2 = find(T_2>=56.32,1);
LH_t2(:,loc2:end)=[];
LH_t2(:,1:loc1)=[];
T_2(loc2:end)=[];
T_2(1:loc1)=[];
Lse_2(loc2:end)=[];
Lse_2(1:loc1)=[];
Lsp_2(loc2:end)=[];
Lsp_2(1:loc1)=[];
Lie_2(loc2:end)=[];
Lie_2(1:loc1)=[];
Lca_2(loc2:end)=[];
Lca_2(1:loc1)=[];
Lelbfe_2(loc2:end)=[];
Lelbfe_2(1:loc1)=[];
Lps_2(loc2:end)=[];
Lps_2(1:loc1)=[];

cost=zeros(size(LH_t2));
costsum = zeros(1,length(cost));
for i=1:length(LH_t2)

cost(1,i) = LH_t2(1,i);
loc3 = find(LH_lookup(1,:)>=round(LH_t2(2,i)),1);
cost(2,i) = abs(LH_t2(2,i)-LH_lookup(1,loc3));
cost(3,i) = abs(LH_t2(3,i)-LH_lookup(2,loc3));
cost(4,i) = abs(LH_t2(4,i)-LH_lookup(3,loc3));
cost(5,i) = abs(LH_t2(5,i)-LH_lookup(4,loc3));
cost(6,i) = abs(LH_t2(6,i)-LH_lookup(5,loc3));
costsum(i) = cost(3,i)+cost(4,i)+cost(5,i)+cost(6,i);
cost(2:6,i) = cost(2:6,i)/costsum(i);
end

% costindsum = zeros(4,1);

for j=1:4
   costindsum(j,2) = sum(cost(j+2,:)); 
end

figure(3)
subplot(3,1,1)
axis([22 56 -120 180])
hold on
LSE = plot(LH_t2(1,:),LH_t2(2,:),'-r','LineWidth',2,'DisplayName','Shoulder Elevation (SE)');
LSP = plot(LH_t2(1,:),LH_t2(3,:),'-g','LineWidth',2,'DisplayName','Shoulder Plane (SP)');
LIE = plot(LH_t2(1,:),LH_t2(4,:),'-b','LineWidth',2,'DisplayName','Shoulder Int.-Ext. Rotation (IE)');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
lgd = legend([LSE,LSP,LIE],'FontSize',15);
lgd.Orientation = 'horizontal';
subplot(3,1,2)
axis([22 56 -90 90])
hold on
LCA  = plot(LH_t2(1,:),Lca_2,'-c','LineWidth',2,'DisplayName','Carry angle (CA)');
LELBFE  = plot(LH_t2(1,:),LH_t2(5,:),'-m','LineWidth',2,'DisplayName','Elbow Flex.-Ext. (FE)');
LPS = plot(LH_t2(1,:),LH_t2(6,:),'-k','LineWidth',2,'DisplayName','Forearm Pro.-Sup. (PS)');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)
lgd = legend([LELBFE,LPS,LCA],'FontSize',15);
lgd.Orientation = 'horizontal';

subplot(3,1,3)
axis([22 56 0 1])
hold on
plot(cost(1,:),cost(3,:),'-g','LineWidth',2,'DisplayName','SP_{cost}');
plot(cost(1,:),cost(4,:),'-b','LineWidth',2,'DisplayName','IE_{cost}');
plot(cost(1,:),cost(5,:),'-k','LineWidth',2,'DisplayName','PS_{cost}');
plot(cost(1,:),cost(6,:),'-m','LineWidth',2,'DisplayName','Elbow FE_{cost}');
% plot(cost(1,:),costsum,'-r','LineWidth',2,'DisplayName','fe_cost');
% plot(15*t,line,'--k','LineWidth',1);
xlabel('Time [s]','FontSize',15)
ylabel('Angle [deg^o]','FontSize',15)

figure(2)
bar(costindsum)
ylabel('Normalized cost','FontSize',20)
set(gca,'xticklabel',{'Shoulder Plane','Shoulder Int.-Ext. Rotation','Forearm Pronation-Supination','Elbow Flexion-Extension'},'FontSize',20)
lgd3 = legend(['aROM';'rROM'],'FontSize',20);
lgd3.Orientation = 'vertical';
