function BIabdadd = importJCS4therapy(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  BIABDADD = importJCS4therapy(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  BIABDADD = importJCS4therapy(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  BIabdadd = importJCS4therapy("F:\github\wearable-jacket\matlab\game design\data\BI_abdadd.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Dec-2019 10:10:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "LSP", "LSE", "LIE", "LELBFE", "LCA", "LPS", "RSP", "RSE", "RIE", "RELBFE", "RCA", "RPS"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
BIabdadd = readtable(filename, opts);

end