function [VarName1, VarName2, VarName3, VarName4, VarName5, VarName6, VarName7, VarName8, VarName9, VarName10] = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [VARNAME1, VARNAME2, VARNAME3, VARNAME4, VARNAME5, VARNAME6,
%  VARNAME7, VARNAME8, VARNAME9, VARNAME10] = IMPORTFILE1(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as column vectors.
%
%  [VARNAME1, VARNAME2, VARNAME3, VARNAME4, VARNAME5, VARNAME6,
%  VARNAME7, VARNAME8, VARNAME9, VARNAME10] = IMPORTFILE1(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [VarName1, VarName2, VarName3, VarName4, VarName5, VarName6, VarName7, VarName8, VarName9, VarName10] = importfile1("F:\github\wearable-jacket\matlab\IEEE_spmb\data\A\X\0_WISE+turntable_07-09-2019 12-16.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Jul-2019 15:53:53

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
VarName1 = tbl.VarName1;
VarName2 = tbl.VarName2;
VarName3 = tbl.VarName3;
VarName4 = tbl.VarName4;
VarName5 = tbl.VarName5;
VarName6 = tbl.VarName6;
VarName7 = tbl.VarName7;
VarName8 = tbl.VarName8;
VarName9 = tbl.VarName9;
VarName10 = tbl.VarName10;
end